### ISSUE TITLE
(👁ω👁)

### ISSUE THREAD

**Issue by syk0saje** [levitanong/amo#5]
Hii~~

I fixie wixied the JSON-api fucksy wucksie!!! xpp

I repwaced the Prototypes.func wiff a more ~streamylined~ kawaii Pwototypiee.funkywunks object that make the JS go sooper dooper fast!! XD *starts twerking*

Can u pwease merge my pwull wequest senpai?!! UwU

**Comment by levitanong** [comment]
Dear kouhai,

I have not seen any pull request from you. Perhaps you forgot to file it? Post it kudasai, and I will shirabetekuru.

Senpai

**Comment by syk0saje** [comment]
no
